/// Flutter icons DogsBarIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DogsBarIcons
///      fonts:
///       - asset: fonts/DogsBarIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DogsBarIcons {
  DogsBarIcons._();

  static const _kFontFam = 'DogsBarIcons';

  static const IconData takewalk = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData putwalk = const IconData(0xe801, fontFamily: _kFontFam);
}
